services:
  mongo:
    container_name: filebrowser-mongo
    image: docker.io/mongo:latest
    restart: always
    volumes:
      - dbdata:/data/db
    security_opt:
      label: disable
    env_file:
      - .env

  rabbitmq:
    container_name: filebrowser-rabbitmq
    image: docker.io/rabbitmq:3.11.3-alpine
    restart: always
    ports:
      - 15672:15672
    security_opt:
      label: disable

  grpc:
    container_name: filebrowser-grpc
    image: localhost/alvidir/filebrowser:latest-grpc
    restart: always
    security_opt:
      label: disable
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - SERVICE_PORT=8000

  rest:
    container_name: filebrowser-rest
    image: localhost/alvidir/filebrowser:latest-rest
    restart: always
    security_opt:
      label: disable
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - SERVICE_PORT=8090

  agent:
    container_name: filebrowser-agent
    image: localhost/alvidir/filebrowser:latest-agent
    restart: always
    security_opt:
      label: disable
    depends_on:
      - rabbitmq
    env_file:
      - .env

  envoy:
    container_name: filebrowser-envoy
    image: docker.io/envoyproxy/envoy-alpine:v1.21-latest
    restart: always
    volumes:
      - ./envoy:/etc/envoy:ro
    security_opt:
      label: disable
    depends_on:
      - filebrowser
    command: /usr/local/bin/envoy --log-level debug -c /etc/envoy/envoy.yaml

  nginx:
    container_name: filebrowser-nginx
    image: docker.io/nginx:1.23.2-alpine
    restart: always
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    security_opt:
        label: disable
    depends_on:
      - envoy

volumes:
  dbdata:
