services:
    filebrowser:
        container_name: filebrowser
        image: docker.io/filebrowser/filebrowser:v2.21.1
        restart: always
        ports:
            - 8080:80
        security_opt:
            label: disable

    filebrowser-agent:
        container_name: filebrowser
        image: localhost/alvidir/filebrowser-agent:0.1.0