services:
  # mongo:
  #   container_name: filebrowser-mongo
  #   image: docker.io/mongo:latest
  #   restart: always
  #   volumes:
  #     - dbdata:/data/db
  #   security_opt:
  #     label: disable
  #   env_file:
  #     - .env

  rabbitmq:
    container_name: filebrowser-rabbitmq
    image: docker.io/rabbitmq:3.11.3-alpine
    restart: always
    security_opt:
      label: disable

  filebrowser:
    container_name: filebrowser-server
    image: localhost/alvidir/filebrowser:latest
    restart: always
    security_opt:
      label: disable
    depends_on:
      # - mongo
    env_file:
      - .env

  agent:
    container_name: filebrowser-agent
    image: localhost/alvidir/filebrowser:latest-agent
    restart: always
    security_opt:
      label: disable
    depends_on:
      - rabbitmq
    env_file:
      - .env

  envoy:
    container_name: filebrowser-envoy
    image: docker.io/envoyproxy/envoy-alpine:v1.21-latest
    restart: always
    ports:
      - 8080:8080
      - 9901:9901
    volumes:
      - ./envoy:/etc/envoy:ro
    security_opt:
      label: disable
    depends_on:
      - filebrowser
    command: /usr/local/bin/envoy --log-level debug -c /etc/envoy/envoy.yaml

volumes:
  dbdata:
