FROM docker.io/golang:1.19 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o filebrowser-rest cmd/rest/main.go

######## Start a new stage from scratch #######
FROM docker.io/alpine:3.16 

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/filebrowser-rest .

CMD [ "./filebrowser-rest" ]
