FROM docker.io/golang:1.20 as builder

RUN apt update -y

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN PKG_MANAGER=apt make all target=rest

######## Start a new stage from scratch #######
FROM docker.io/alpine:3.17

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/bin/rest/filebrowser-rest .

CMD [ "./filebrowser-rest" ]
