FROM docker.io/golang:1.19 as builder

RUN apt update && \
    apt install -y protobuf-compiler

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN make go-install && \
    make proto -B

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o filebrowser cmd/filebrowser/main.go

######## Start a new stage from scratch #######
FROM docker.io/alpine:3.15.5  

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/filebrowser .

CMD [ "./filebrowser" ]
