FROM docker.io/golang:latest as builder

RUN apt update && \
    apt install -y protobuf-compiler

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN make install && \
    make proto -B

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o filebrowser-mq-users cmd/mq-users/main.go

######## Start a new stage from scratch #######
FROM docker.io/alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/filebrowser-mq-users .

CMD [ "./filebrowser-mq-users" ]
