name: Run tests

on:
  - push
  - pull_request

jobs:
  run_unitary_tests:
    name: Run unitary tests
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install protoc
        uses: arduino/setup-protoc@v1
        with:
          version: "3.x"

      - name: Install plugins
        run: make install

      - name: Generate protos
        run: make proto -B

      - name: Test
        run: go test -v -race ./...

release_version:
  name: Release version
  runs-on: ubuntu-latest

  needs:
    - run_unitary_tests

  if: ${{ github.ref == 'refs/heads/main' && !contains(join(needs.*.conclusion), 'failure') }}

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create tag
      id: tagging
      uses: anothrNick/github-tag-action@1.40.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tagging.outputs.new_tag }}
        token: ${{ secrets.PAT }}WWWWWW
